[project]
name = "enfys-ob-egse"
version = "0.1.0"
description = "Python egse for the Enfys Optical Box"
authors = [ 
    { 
        name="Barry Whiteside", 
        email="34492784+Chaldene@users.noreply.github.com" 
    }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bitstruct>=8.19.0",
    "crc8>=0.2.1",
    "nicegui",
    "plotly>=6.5.0",
    "pyserial>=3.5",
    "pywebview>=6.2.1",
    "pywinauto>=0.6.9",
    "ruff>=0.9.4",
    "streamlit>=1.50.0",
    "streamlit-extras>=0.7.8",
]

[dependency-groups]
dev = ["pytest>=8.3.4", "ruff>=0.9.4"]

[tool.pytest.ini_options]
pythonpath = "src"
