exclude = [".venv", ".git", "__pycache__", ".vscode", "logs"]
line-length = 120
indent-width = 4
target-version = "py312"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-coma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"