# List of available CMD IDs and response types using
# names according to OB-EB Data ICD

cmd_ids = {
    0x0: "HK_Request",
    0x1: "NACK",
    0x2: "Clear_Errors",
    0x3: "Set_Errors",
    0x4: "Power_Control",
    0x5: "Heater_Control",
    0x6: "Set_Mech_SP",
    0x7: "Set_Detec_SP",
    0x8: "Set_MTR_Param",
    0x9: "MTR_Mov_Pos",
    0xA: "MTR_Mov_Neg",
    0xB: "MTR_Halt",
    0xC: "MTR_Homing",
    0xD: "Set_HK_Samples",
    0xE: "SCI_Offset",
    0xF: "SCI_Request",
}


# Enfys telecommand definitions used by the CmdTool script sender.
# Keys match logical TC names and values contain formatting/verification metadata.
enfys_tc_defs = {
    "RET": {
        "block_id": 0x00,
        "cmdtool_name": "ENFYS_RET",
        "aliases": (),
        "arg_count": (6, 6),
        "valid_states": ("SAFE", "STANDBY", "ACQUISITION"),
        "verify": {"accepted_increment": 1, "last_tc_type": 0x00},
    },
    "REQUEST_HK": {
        "block_id": 0x01,
        "cmdtool_name": "ENFYS_REQUEST_HK",
        "aliases": (),
        "arg_count": (1, 1),
        "valid_states": ("SAFE", "STANDBY", "ACQUISITION"),
        "verify": {"accepted_increment": 1, "last_tc_type": 0x01},
    },
    "PATCH": {
        "block_id": 0x02,
        "cmdtool_name": "ENFYS_PATCH",
        "aliases": (),
        "arg_count": (3, 2000),
        "valid_states": ("SAFE",),
        "verify": {"accepted_increment": 1, "last_tc_type": 0x02},
    },
    "DUMP": {
        "block_id": 0x03,
        "cmdtool_name": "ENFYS_DUMP",
        "aliases": (),
        "arg_count": (3, 3),
        "valid_states": ("SAFE",),
        "verify": {"accepted_increment": 1, "last_tc_type": 0x03},
    },
    "SET_HK_RATE": {
        "block_id": 0x04,
        "cmdtool_name": "ENFYS_SET_HK_RATE",
        "aliases": (),
        "arg_count": (2, 2),
        "valid_states": ("SAFE", "STANDBY", "ACQUISITION"),
        "verify": {"accepted_increment": 1, "last_tc_type": 0x04},
    },
    "MONITOR_ADDR": {
        "block_id": 0x05,
        "cmdtool_name": "ENFYS_MONITOR_ADDR",
        "aliases": (),
        "arg_count": (2, 2),
        "valid_states": ("SAFE", "STANDBY", "ACQUISITION"),
        "verify": {"accepted_increment": 1, "last_tc_type": 0x05},
    },
    "ABORT": {
        "block_id": 0x06,
        "cmdtool_name": "ENFYS_ABORT",
        "aliases": (),
        "arg_count": (1, 1),
        "valid_states": ("ACQUISITION",),
        "verify": {"accepted_increment": 1, "last_tc_type": 0x06},
    },
    "GENERIC_TC": {
        "block_id": 0x07,
        "cmdtool_name": "ENFYS_GENERIC_TC",
        "aliases": (),
        "arg_count": (2, 17),
        "valid_states": ("SAFE", "STANDBY", "ACQUISITION"),
        "verify": {"accepted_increment": 1, "last_tc_type": 0x07},
    },
    "SAFE": {
        "block_id": 0x08,
        "cmdtool_name": "ENFYS_SAFE",
        "aliases": (),
        "arg_count": (1, 1),
        "valid_states": ("STANDBY", "ACQUISITION"),
        "verify": {"accepted_increment": 1, "last_tc_type": 0x08},
    },
    "STANDBY": {
        "block_id": 0x09,
        "cmdtool_name": "ENFYS_STANDBY",
        "aliases": (),
        "arg_count": (2, 2),
        "valid_states": ("SAFE",),
        "verify": {"accepted_increment": 1, "last_tc_type": 0x09},
    },
    "ACQUISITION": {
        "block_id": 0x0A,
        "cmdtool_name": "ENFYS_ACQUISITION",
        "aliases": (),
        "arg_count": (1, 1),
        "valid_states": ("STANDBY",),
        "verify": {"accepted_increment": 1, "last_tc_type": 0x0A},
    },
    "SET_MOTOR_CONFIGS": {
        "block_id": 0x0B,
        "cmdtool_name": "ENFYS_SET_MOTOR_CONFIGS",
        "aliases": (),
        "arg_count": (10, 10),
        "valid_states": ("STANDBY",),
        "verify": {"accepted_increment": 1, "last_tc_type": 0x0B},
    },
    "SET_HEATER_CONFIGS": {
        "block_id": 0x0C,
        "cmdtool_name": "ENFYS_SET_HEATER_CONFIGS",
        "aliases": (),
        "arg_count": (5, 5),
        "valid_states": ("STANDBY",),
        "verify": {"accepted_increment": 1, "last_tc_type": 0x0C},
    },
    "SET_ACQ_CONFIGS": {
        "block_id": 0x0D,
        "cmdtool_name": "ENFYS_SET_ACQ_CONFIGS",
        "aliases": (),
        "arg_count": (14, 14),
        "valid_states": ("STANDBY",),
        "verify": {"accepted_increment": 1, "last_tc_type": 0x0D},
    },
    "SET_TEC_SETPOINT": {
        "block_id": 0x0E,
        "cmdtool_name": "ENFYS_SET_TEC_POINT",
        "aliases": ("ENFYS_SET_TEC_SETPOINT",),
        "arg_count": (2, 2),
        "valid_states": ("STANDBY", "ACQUISITION"),
        "verify": {"accepted_increment": 1, "last_tc_type": 0x0E},
    },
    "SET_FDIR_LIMITS": {
        "block_id": 0x0F,
        "cmdtool_name": "ENFYS_SET_FDIR_LIMITS",
        "aliases": (),
        "arg_count": (69, 69),
        "valid_states": ("SAFE", "STANDBY", "ACQUISITION"),
        "verify": {"accepted_increment": 1, "last_tc_type": 0x0F},
    },
    "EN_MECH_BOARD": {
        "block_id": 0x10,
        "cmdtool_name": "ENFYS_EN_MECH_BOARD",
        "aliases": (),
        "arg_count": (1, 1),
        "valid_states": ("STANDBY",),
        "verify": {"accepted_increment": 1, "last_tc_type": 0x10},
    },
    "EN_DET_BOARD": {
        "block_id": 0x11,
        "cmdtool_name": "ENFYS_EN_DET_BOARD",
        "aliases": (),
        "arg_count": (1, 1),
        "valid_states": ("STANDBY",),
        "verify": {"accepted_increment": 1, "last_tc_type": 0x11},
    },
    "EN_MECH_HEATER": {
        "block_id": 0x12,
        "cmdtool_name": "ENFYS_EN_MECH_HEATER",
        "aliases": (),
        "arg_count": (1, 1),
        "valid_states": ("STANDBY",),
        "verify": {"accepted_increment": 1, "last_tc_type": 0x12},
    },
    "EN_DET_HEATER": {
        "block_id": 0x13,
        "cmdtool_name": "ENFYS_EN_DET_HEATER",
        "aliases": (),
        "arg_count": (1, 1),
        "valid_states": ("STANDBY",),
        "verify": {"accepted_increment": 1, "last_tc_type": 0x13},
    },
    "EN_OB5V": {
        "block_id": 0x14,
        "cmdtool_name": "ENFYS_OB5V_TOGGLE",
        "aliases": (),
        "arg_count": (1, 1),
        "valid_states": ("STANDBY",),
        "verify": {"accepted_increment": 1, "last_tc_type": 0x14},
    },
    "OB_PARK": {
        "block_id": 0x15,
        "cmdtool_name": "ENFYS_OB_PARK",
        "aliases": (),
        "arg_count": (1, 1),
        "valid_states": ("STANDBY", "ACQUISITION"),
        "verify": {"accepted_increment": 1, "last_tc_type": 0x15},
    },
    "OB_HOMING": {
        "block_id": 0x16,
        "cmdtool_name": "ENFYS_OB_HOMING",
        "aliases": (),
        "arg_count": (1, 1),
        "valid_states": ("STANDBY",),
        "verify": {"accepted_increment": 1, "last_tc_type": 0x16},
    },
    "OB_HK": {
        "block_id": 0x17,
        "cmdtool_name": "ENFYS_OB_HK",
        "aliases": (),
        "arg_count": (1, 1),
        "valid_states": ("STANDBY", "ACQUISITION"),
        "verify": {"accepted_increment": 1, "last_tc_type": 0x17},
    },
    "CHECK_MEMORY": {
        "block_id": 0x64,
        "cmdtool_name": "ENFYS_CHECK_MEMORY",
        "aliases": (),
        "arg_count": (3, 3),
        "valid_states": ("SAFE", "STANDBY"),
        "verify": None,
        "development_only": True,
    },
    "GOTO": {
        "block_id": 0x65,
        "cmdtool_name": "ENFYS_GOTO",
        "aliases": (),
        "arg_count": (2, 2),
        "valid_states": ("SAFE",),
        "verify": None,
        "development_only": True,
    },
    "COPY_MEMORY": {
        "block_id": 0x66,
        "cmdtool_name": "ENFYS_COPY_MEMORY",
        "aliases": (),
        "arg_count": (4, 4),
        "valid_states": ("SAFE",),
        "verify": None,
        "development_only": True,
    },
    "SWITCH_RS422": {
        "block_id": 0x67,
        "cmdtool_name": "ENFYS_SWITCH_RS422",
        "aliases": (),
        "arg_count": (1, 1),
        "valid_states": ("SAFE", "STANDBY", "ACQUISITION"),
        "verify": None,
        "development_only": True,
    },
    "SET_TEC_CURRENT": {
        "block_id": 0x68,
        "cmdtool_name": "ENFYS_SET_TEC_CURRENT",
        "aliases": (),
        "arg_count": (2, 2),
        "valid_states": ("STANDBY", "ACQUISITION"),
        "verify": None,
        "development_only": True,
    },
}
