# Packet ID breakdown (see doc table 5-5)
packet_id_struct = [
    ("BLOCK_TYPE", "u1"),
    ("TM_CRITICALITY", "u2"),
    ("MMS_DEST", "u1"),
    ("INSTR_ID", "u4"),
    ("TM_TYPE_ID", "u6"),
    ("SEQ_FLAG", "u2"),
]
# Get packing formats print(''.join(i[1] for i in hk))
# Get names print(''.join(i[1] for i in hk))

# HK starting from byte 0
# Bitfields have the suffix "_Byte" to indicate they'll be unpacked elsewhere in the code.
hk = [
    ("MOD_ID", "u3"),
    ("UNUSED1", "u1"),
    ("CMD_ID", "u4"),
    ("CMD_CNT", "u8"),
    ("ERROR_BYTE", "u8"),
    ("UNUSED2", ">u32"),
    ("ERROR_MTR", "u8"),
    ("MTR_ERR_MSK_BYTE", "u8"),
    ("MTR_FLAGS_BYTE", "u8"),
    ("MTR_ABS_STEPS", ">u16"),
    ("MTR_REL_STEPS", ">s16"),
    ("UNUSED3", ">u1"),
    ("MTR_CURRENT", "u7"),
    ("UNUSED4", ">u6"),
    ("MTR_GUARD_SELECT", "u2"),
    ("MTR_CHOP", "u8"),
    ("UNUSED5", "u4"),
    ("MTR_SPEED", "u4"),
    ("UNUSED6", ">u88"),
    ("PWR_STAT", "u8"),
    ("THRM_STATUS_BYTE", "u8"),
    ("THRM_MECH_OFF_SP", ">u16"),
    ("THRM_MECH_ON_SP", ">u16"),
    ("THRM_DET_OFF_SP", ">u16"),
    ("THRM_DET_ON_SP", ">u16"),
    ("SWIR_OFFSET", ">u16"),
    ("MWIR_OFFSET", ">u16"),
    ("HK_V_3V3", ">u16"),
    ("HK_V_1V5", ">u16"),
    ("DIGITAL_TRP", ">u16"),
    ("DETEC_TRP", ">u16"),
    ("MECH_TRP", ">u16"),
    ("MOTOR_TRP", ">u16"),
    ("HK_MECH_CUR", ">u16"),
    ("UNUSED_ADC", ">u16"),
    ("HK_SAMPLES", "u8"),
    ("UNUSED7", ">u40"),
    ("CRC8", "u8"),
]


# TODO: Determine if MSB or LSB

error_struct = [
    ("IPI", "u1"),
    ("IOS", "u1"),
    ("ICR", "u1"),
    ("UNUSED1", "u1"),
    ("MOR", "u1"),
    ("UNUSED2", "u1"),
    ("TMO", "u1"),
    ("IPA", "u1"),
]

mtr_error_struct = [
    ("UNUSED", "u4"),
    ("CD", "u1"),
    ("AB", "u1"),
    ("ABS", "u1"),
    ("DSE", "u1"),
]
mtr_err_msk_struct = [
    ("IG_B", "u1"),
    ("IG_O", "u1"),
    ("UNUSED", "u2"),
    ("M_CD", "u1"),
    ("M_AB", "u1"),
    ("M_ABS", "u1"),
    ("M_DSE", "u1"),
]

mtr_flag_struct = [
    ("UNUSED1", "u1"),
    ("CAL", "u1"),
    ("UNUSED2", "u1"),
    ("DIR", "u1"),
    ("OUTER", "u1"),
    ("BASE", "u1"),
    ("MOVING", "u1"),
    ("HOMING", "u1"),
]

thrm_status_struct = [
    ("HDS", "u1"),
    ("HMS", "u1"),
    ("UNUSED", "u1"),
    ("S", "u1"),
    ("DM", "u1"),
    ("DA", "u1"),
    ("MM", "u1"),
    ("MA", "u1"),
]

ack_struct = [
    ("MOD_ID", "u3"),
    ("UNUSED1", "u1"),
    ("CMD_ID", "u4"),
    ("ERROR_BYTE", "u8"),
    ("PARAM1", "u8"),
    ("PARAM2", "u8"),
    ("PARAM3", "u8"),
    ("PARAM4", "u8"),
    ("PARAM5", "u8"),
    ("PARAM6", "u8"),
    ("CRC8", "u8"),
]

nack = [
    ("MOD_ID", "u3"),
    ("CMD_ID", "u5"),
    ("ERROR_BYTE", "u8"),
]

sci = [
    ("MOD_ID", "u3"),
    ("UNUSED1", "u1"),
    ("CMD_ID", "u4"),
    ("CMD_CNT", "u8"),
    ("ERROR_BYTE", "u8"),
    ("MTR_ABS_STEPS", ">u16"),
    ("THRM_STATUS_BYTE", "u8"),
    ("SWIR_OFFSET", ">u16"),
    ("MWIR_OFFSET", ">u16"),
    ("SCI_ADC_SAMPLES", "u8"),
    ("SCI_ADC_SKIP", "u8"),
    ("SWIR_HIGH", ">u16"),
    ("SWIR_MED", ">u16"),
    ("SWIR_LOW", ">u16"),
    ("MWIR_HIGH", ">u16"),
    ("MWIR_MED", ">u16"),
    ("MWIR_LOW", ">u16"),
    ("HT_SINK_TEMP", ">u16"),
    ("SWIR_TEMP", ">u16"),
    ("CRC", "u8"),
]


eb_hk = [
    ("PATTERN", "u32"),
    ("PACKET_ID", "u16"),
    ("LOBT_RET_TIME", ">u48"),
    ("BLOCK_LENGTH", "u16"),
    ("TCS_ACCEPTED", "u16"),
    ("TCS_REJECTED", "u16"),
    ("INSTRUMENT_STATUS_FLAGS", "u16"),
    ("ONGOING_PROCESS_FLAGS", "u16"),
    ("ERROR_FLAGS", "u16"),
    ("CURRENT_OPERATING_STATE", "u8"),
    ("LAST_PATCH_CRC", "u16"),
    ("CALC_LAST_PATCH_CRC", "u16"),
    ("SPARES_BLOCK_1", ">u96"),
    ("CHECK_MEM_CRC", "u16"),
    ("WARNING_FLAGS", "u16"),
    ("FDIR_ALARM_FLAGS", "u32"),
    ("FDIR_WARNING_FLAGS", "u32"),
    ("LAST_RECEIVED_RET_S", "u32"),
    ("LAST_RECEIVED_RET_MS", "u16"),
    ("LOBT_AT_LAST_RET_SYNC_S", "u32"),
    ("LOBT_AT_LAST_RET_SYNC_MS", "u16"),
    ("WORST_LOOP_TIME_SINCE_LAST_HK_TX", "u16"),
    ("FLASH_WRITE_FAILURES", "u16"),
    ("TCS_RECEIVED", "u16"),
    ("LAST_TC_TYPE", "u8"),
    ("LAST_OB_TC_TYPE", "u8"),
    ("LAST_OB_TC_ERROR", "u8"),
    ("SPARES_BLOCK_2", "u16"),
    ("LAST_TC_QUALIFIER", "u8"),
    ("LAST_TC_FIRST_DATA_WORD", "u32"),
    ("LAST_TC_SECOND_DATA_WORD", "u32"),
    ("LAST_BUT_1_TC_TYPE", "u8"),
    ("LAST_BUT_1_OB_TC_TYPE", "u8"),
    ("LAST_BUT_1_OB_TC_ERROR", "u8"),
    ("SPARES_BLOCK_3", "u16"),
    ("LAST_BUT_1_TC_QUALIFIER", "u8"),
    ("LAST_BUT_1_TC_FIRST_DATA_WORD", "u32"),
    ("LAST_BUT_1_TC_SECOND_DATA_WORD", "u32"),
    ("ASW_IMAGE_NUMBER_RUNNING", "u8"),
    ("SOFTWARE_MAJOR_VERSION", "u8"),
    ("SOFTWARE_MINOR_VERSION", "u8"),
    ("SOFTWARE_PATCH_VERSION", "u8"),
    ("HK_PACKETS_SENT", "u16"),
    ("CURRENT_HK_TIME_INTERVAL", "u16"),
    ("SCIENCE_PACKETS_SENT", "u16"),
    ("MEASUREMENT_CURVE_SELECTED", "u8"),
    ("TEC_SETPOINT", "u16"),
    ("EB_MEAS_MAIN_12V", "u16"),
    ("EB_MEAS_MAIN_NEG12V", "u16"),
    ("EB_MEAS_5V", "u16"),
    ("EB_MEAS_3V3", "u16"),
    ("EB_MEAS_TEC_RAIL", "u16"),
    ("EB_0V_ADC_READING", "u16"),
    ("EB_MCU_INTERNAL_TEMP", "u16"),
    ("EB_PELTIER_TEMP", "u16"),
    ("EB_INTERNAL_TRP_TEMP", "u16"),
    ("EB_PSU_BOARD_TEMP", "u16"),
    ("EB_TEC_DRIVE_CURRENT", "u16"),
    ("EB_TEC_DAC_OUTPUT", "u16"),
    ("OB_HK_ID", "u8"),
    ("OB_COMMAND_COUNT", "u8"),
    ("OB_LAST_ERROR", "u8"),
    ("OB_POWER_STATUS", "u8"),
    ("SPARES_BLOCK_4", "u32"),
    ("OB_MOTOR_ERROR", "u8"),
    ("OB_MOTOR_ABS_STEPS", "u16"),
    ("OB_MOTOR_REL_STEPS", "u16"),
    ("OB_MOTOR_STATUS_FLAGS", "u8"),
    ("OB_MOTOR_GUARD_TIME", "u16"),
    ("OB_MOTOR_PWM_DUTY", "u8"),
    ("OB_MOTOR_PWM_RATE", "u16"),
    ("OB_MOTOR_RECVAL", "u8"),
    ("OB_MOTOR_SPISPSEL", "u16"),
    ("OB_MOTOR_CURRENT", "u16"),
    ("OB_SPEED", "u8"),
    ("OB_MOTOR_ERROR_MASK", "u8"),
    ("OB_MOTOR_RECIRC", "u8"),
    ("SPARES_BLOCK_5", ">u24"),
    ("OB_THERMAL_STATUS", "u8"),
    ("OB_THERMAL_MECH_MAX", "u16"),
    ("OB_THERMAL_MECH_MIN", "u16"),
    ("OB_THERMAL_DET_MAX", "u16"),
    ("OB_THERMAL_DET_MIN", "u16"),
    ("OB_SWIR_OFFSET", ">u16"),
    ("OB_MWIR_OFFSET", ">u16"),
    ("OB_3V3_VOLTAGE", "u16"),
    ("OB_1V5_VOLTAGE", "u16"),
    ("OB_DIGITAL_TRP", "u16"),
    ("OB_DETECTOR_TRP", "u16"),
    ("OB_MECHANISM_TRP", "u16"),
    ("OB_MOTOR_TRP", "u16"),
    ("OB_MECH_CURRENT", "u16"),
    ("OB_ADC_SPARE", "u16"),
    ("HK_NUMBER_OF_SAMPLES", "u8"),
    ("SPARES_BLOCK_7", ">u40"),
    ("OB_HK_CRC8", "u8"),
    ("WATCH_POINT_ADDRESS_DATA", "u32"),
    ("WATCH_POINT_ADDRESS", "u32"),
    ("HK_PACKET_CRC", "u16"),
    ("PADDING", "u352"),
]

eb_instrument_status_flags = [
    ("HOMING_COMPLETE", "u1"),
    ("DETECTOR_WARM", "u1"),
    ("MECHANISM_WARM", "u1"),
    ("TEC_AT_SETPOINT", "u1"),
    ("MECHANISM_PARKED", "u1"),
    ("OB_5V_ENABLED", "u1"),
    ("OB_MECHANISM_BOARD_ENABLED", "u1"),
    ("OB_DETECTOR_BOARD_ENABLED", "u1"),
    ("OB_MECHANISM_HEATER_ENABLED", "u1"),
    ("OB_DETECTOR_HEATER_ENABLED", "u1"),
    ("MEASUREMENT_CONFIGS_SET", "u1"),
    ("MOTOR_CONFIGS_SET", "u1"),
    ("HEATER_CONFIGS_SET", "u1"),
    ("RET_SYNCHRONISED", "u1"),
    ("POST_COMPLETE_NO_WARNINGS", "u1"),
    ("TEC_ENABLED", "u1"),
]

eb_warning_flags = [
    ("GENERAL_ERROR", "u1"),
    ("OB_GENERAL_ERROR", "u1"),
    ("EB_FDIR_ALARM", "u1"),
    ("OB_FDIR_ALARM", "u1"),
    ("WATCHDOG_TIMEOUT_DETECTED", "u1"),
    ("NO_RET_RECEIVED", "u1"),
    ("NO_HEALTHY_ASW_IMAGE", "u1"),
    ("OB_MOTOR_ERROR", "u1"),
    ("OB_UNRESPONSIVE", "u1"),
    ("OB_STEP_COUNT_MISMATCH", "u1"),
    ("PATCH_WRITING_ERROR", "u1"),
    ("RS422_RECEIVE_ERROR", "u1"),
    ("RS422_TRANSMIT_ERROR", "u1"),
    ("RS485_RECEIVE_ERROR", "u1"),
    ("RS485_TRANSMIT_ERROR", "u1"),
    ("RESERVED", "u1"),
]

eb_fdir_flags = [
    ("RESERVED_0", "u1"),
    ("EB_PLUS_12V_SUPPLY", "u1"),
    ("EB_MINUS_12V_SUPPLY", "u1"),
    ("EB_PLUS_5V_SUPPLY", "u1"),
    ("EB_PLUS_3V3_SUPPLY", "u1"),
    ("EB_TEC_SUPPLY", "u1"),
    ("EB_0V", "u1"),
    ("PROCESSOR_INTERNAL_TEMPERATURE", "u1"),
    ("PELTIER_TEMPERATURE", "u1"),
    ("INTERNAL_TRP_TEMPERATURE", "u1"),
    ("PSU_BOARD_TEMPERATURE", "u1"),
    ("TEC_DRIVE_CURRENT", "u1"),
    ("FPGA_IO_POWER_SUPPLY", "u1"),
    ("FPGA_CORE_POWER_SUPPLY", "u1"),
    ("DIGITAL_BOARD_TRP", "u1"),
    ("DETECTOR_BOARD_TRP", "u1"),
    ("MECH_BOARD_TRP", "u1"),
    ("MOTOR_TRP", "u1"),
    ("RESERVED_1", "u14"),
]

post_hk = [
    ("PATTERN", "u32"),
    ("PACKET_ID", "u16"),
    ("LOBT_RET_TIME", ">u48"),
    ("BLOCK_LENGTH", "u16"),
    ("POST_ERROR_FLAGS", "u16"),
    ("POST_WARNING_FLAGS", "u16"),
    ("NUM_BAD_FLASH_BLOCKS", "u16"),
    ("NUM_BAD_SRAM_BLOCKS", "u16"),
    ("ASW_IMAGE_1_CRC", "u16"),
    ("ASW_IMAGE_2_CRC", "u16"),
    ("ASW_IMAGE_3_CRC", "u16"),
    ("ASW_IMAGE_4_CRC", "u16"),
    ("ASW_IMAGE_5_CRC", "u16"),
    ("BSW_IMAGE_CRC", "u16"),
    ("MEASUREMENT_TABLE_CRC", "u16"),
    ("TM_12V", "u16"),
    ("TM_NEG12V", "u16"),
    ("TM_5V", "u16"),
    ("TM_3V3", "u16"),
    ("EB_PROCESSOR_TEMP", "u16"),
    ("TEC_DETECTOR_TEMP", "u16"),
    ("EB_INTERNAL_TRP_TEMP", "u16"),
    ("PSU_PRT_TEMP", "u16"),
    ("PADDING", ">u1632"),
]

eb_sci = [
    ("PATTERN", "u32"),
    ("PACKET_ID", "u16"),
    ("LOBT_RET_TIME", ">u48"),
    ("BLOCK_LENGTH", "u16"),
    ("PACKET_NUMBER", "u16"),
    ("SOL_NO", "u16"),
    ("MEASUREMENT_TYPE_ID", "u16"),
    ("MEASUREMENT_RUN_NO", "u16"),
    ("START_TIME_S", "u32"),
    ("START_TIME_MS", "u16"),
    ("END_TIME_S", "u32"),
    ("END_TIME_MS", "u16"),
    ("SWIR_OFFSET", ">u16"),
    ("MWIR_OFFSET", ">u16"),
    ("HEATSINK_START_TEMP", ">u16"),
    ("HEATSINK_END_TEMP", ">u16"),
    ("SWIR_START_TEMP", ">u16"),
    ("SWIR_END_TEMP", ">u16"),
    ("MWIR_START_TEMP", ">u16"),
    ("MWIR_END_TEMP", ">u16"),
    ("START_MTR_ABS_STEPS", ">u16"),
    ("SAMPLE_DELAY", ">u16"),
    ("FPGA_SAMPLES", ">u8"),
    ("RESERVED_0", ">u8"),
    ("ACQUISITION_MODE", "u2"),
    ("AVERAGING_NUMBER", "u2"),
    ("RESERVED_1", ">u4"),
    ("SCI_DATA", "u65080"),
]
eb_sci_header = [
    ("PATTERN", "u32"),
    ("PACKET_ID", "u16"),
    ("LOBT_RET_TIME", ">u48"),
    ("BLOCK_LENGTH", "u16"),
    ("PACKET_NUMBER", "u16"),
    ("SOL_NO", "u16"),
    ("MEASUREMENT_TYPE_ID", "u16"),
    ("MEASUREMENT_RUN_NO", "u16"),
    ("START_TIME_S", "u32"),
    ("START_TIME_MS", "u16"),
    ("END_TIME_S", "u32"),
    ("END_TIME_MS", "u16"),
    ("SWIR_OFFSET", ">u16"),
    ("MWIR_OFFSET", ">u16"),
    ("HEATSINK_START_TEMP", ">u16"),
    ("HEATSINK_END_TEMP", ">u16"),
    ("SWIR_START_TEMP", ">u16"),
    ("SWIR_END_TEMP", ">u16"),
    ("MWIR_START_TEMP", ">u16"),
    ("MWIR_END_TEMP", ">u16"),
    ("START_MTR_ABS_STEPS", ">u16"),
    ("SAMPLE_DELAY", ">u16"),
    ("FPGA_SAMPLES", ">u8"),
    ("RESERVED_0", ">u8"),
    ("ACQUISITION_MODE", "u2"),
    ("AVERAGING_NUMBER", "u2"),
    ("RESERVED_1", ">u4"),
]
dump_data = [
    ("PATTERN", "u32"),
    ("PACKET_ID", "u16"),
    ("LOBT_RET_TIME", ">u48"),
    ("BLOCK_LENGTH", "u16"),
    ("MEM_ADDR", "u32"),
    ("MEM_SIZE", "u32"),
    ("DUMP_DATA", "u65376"),
]
sci_data = [
    ("ABS_STEPS", ">u16"),
    ("SWIR_LOW", ">u16"),
    ("SWIR_MED", ">u16"),
    ("SWIR_HIGH", ">u16"),
    ("MWIR_LOW", ">u16"),
    ("MWIR_MED", ">u16"),
    ("MWIR_HIGH", ">u16"),
]
